---
title: "Practical Machine Learning Course Project"
author: "Laura Sedman"
date: "09/13/2014"
output: html_document
---



```{r getData}
url1 <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
url2 <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

if (!file.exists("pml-training.csv")) {
        download.file(url1, destfile="pml-training.csv", method="curl")
}

if (!file.exists("pml-testing.csv")) {
        download.file(url2, destfile="pml-testing.csv", method="curl")
}

data <- read.csv("pml-training.csv")
finalTesting <- read.csv("pml-testing.csv")
```


```{r splitData}

library(caret)

set.seed(27)
inTrain <- createDataPartition(y = data$classe, p=0.7, list=FALSE)
train <- data[inTrain,]
test <- data[-inTrain,]
rm(inTrain)
rm(data)
```

``` {r exploreData and preprocess}
str(train)
NAs <- colSums(is.na(train))
NAs <- names(subset(NAs, NAs != 0))
train <- train[ , !names(train) %in% NAs] 
test <- test[ , !names(test) %in% NAs] 
finalTesting <- finalTesting[ , !names(finalTesting) %in% NAs] 
rm(NAs)

train <- train[, -c(1, 3:5)]
noVar <- nearZeroVar(train)
train <- train[, -noVar]

test <- test[, -c(1, 3:5)]
test <- test[, -noVar]

finalTesting <- finalTesting[, -c(1, 3:5)]
finalTesting <- finalTesting[, -noVar]
```

``` {r LDA}
modelFit <- train(classe ~ ., data=train, preProcess = "BoxCox", method="lda")
